### ISSUE TITLE
Error Message for too large images

### ISSUE THREAD

**Issue by ertz10** [ErlerPhilipp/Pix2Model#133]
There is currently an ugly error message in the upload field for images that are too large. A specific human readable error message should be implemented.

Image for reference
![YCMYZLr](https://github.com/ErlerPhilipp/Pix2Model/assets/35370970/37a88050-39bf-4b5d-98f8-2258ba9472b9)

**Comment by ErlerPhilipp** [comment]
Quick googling gives "client_max_body_size" in the nginx config as a possible reason. We use 0 (=disabled) since forever. So, that's probably not the reason.

Checking HDD space... Looks ok.

I think it's time for Max.

**Comment by ErlerPhilipp** [comment]
maybe permission errors?
https://www.cyberciti.biz/faq/linux-unix-bsd-nginx-413-request-entity-too-large/

**Comment by ErlerPhilipp** [comment]
reason was the new proxy (nginx settings)
