### ISSUE TITLE
unable to start after deployment

### ISSUE THREAD

**Issue by yuancaimaiyi** [ErlerPhilipp/Pix2Model#194]
@ErlerPhilipp 

Hi，ErlerPhilipp .After I deploy this program, opening https://localhost/ and https://localhost/dashboard/ on the web page are invalid(ERR_CONNECTION_CLOSED）. The deployment results are as follows:
![image](https://github.com/ErlerPhilipp/Pix2Model/assets/28293910/b85b622c-9deb-462e-b0c5-c7af89c8334e)
How should I solve it? Thanks

**Comment by ErlerPhilipp** [comment]
The logs looks fine. You can ignore the warning.

Which browser are you using? Some browsers (Chrome?) block connections with invalid SSL keys. Did you install a valid certificate? On Firefox, you can choose to accept the risk and connect nevertheless.

If that's not the issue, maybe it's the wrong port. Are you using the current nginx.conf from the repo? You could try switching to HTTP (port 80 or 8082, avoid SSL certificates). Please see the readme>setup for more details. I hope it is still correct and understandable. If not, please let me know.

**Comment by yuancaimaiyi** [comment]
@ErlerPhilipp Hello, I have solved it. I use localhost:8082 and there is no problem. In addition, I would like to ask, this code can only upload 100 images. If I want to upload more, such as 1000 images, where should I modify it?

**Comment by ErlerPhilipp** [comment]
@yuancaimaiyi thanks for testing and reporting! I added a note for port 8082 to the readme.

I'm not too deep in the Flask part so take this with a grain of salt. I think you need to change these places:
1. Line 29 and 31 in /web/src/upload/UploadComponent.jsx
2. Line 6 in /images_to_mesh/app/config.py to allow more data overall

You'll need to run the Flask part again. I think this requires a docker compose call without cache. Make sure to also refresh cached Data in the Browser (Ctrl+F5).

Btw. we're currently working on adding support for texturing. This is in the openMvs_color branch and will be merged into main soon. We replace COLMAP's MVS and reconstruction part with OpenMVS. The geometric quality seems similar so far, but textures are much better suited for decimated meshes.

**Comment by yuancaimaiyi** [comment]
@ErlerPhilipp  
Thank you very much for your suggestions. I have modified these places, but I still cannot upload more images (I uploaded 500 images here and there is no response when I click submit), as follows:
![image](https://github.com/ErlerPhilipp/Pix2Model/assets/28293910/921de753-4318-4dac-950c-a7c7f5694a2f)
![image](https://github.com/ErlerPhilipp/Pix2Model/assets/28293910/a1a79ea7-5893-4a20-bb8a-d288f5cb18c6)

![image](https://github.com/ErlerPhilipp/Pix2Model/assets/28293910/a78675cd-b2da-4128-93e8-d60dbc60cc3c)

**Comment by ErlerPhilipp** [comment]
The error message sounds like the number of files might be ok but the file size is not ok. 

MAX_FILE_SIZE_IN_MB = 200000 would be 200GB, which is maybe too much. If really upload that much, it probably needs to fit in your RAM all at once. 

Also, in UploadComponent.jsx is the maxFilesize parameter. This should be ok with 50 (MB per file?) but I can be wrong.

Can you check the upload limits? If it works with a certain number of files, total size and size per file?
If it fails with <100 files, there is probably something still cached and not up-to-date with your changed code.

**Comment by ErlerPhilipp** [comment]
@yuancaimaiyi could you solve the problem? Do you need more help?

**Comment by ErlerPhilipp** [comment]
please re-open if you need more help
