### ISSUE TITLE
WP 5.2: better colors

### ISSUE THREAD

**Issue by ErlerPhilipp** [ErlerPhilipp/Pix2Model#22]
"Nearest Neighbor Vertex Colors (NNVC) ist sehr einfach und wird bei kleineren Grid-Resolutions schlechte Ergebnisse liefern. Mit Philipp, Stefan und/oder Michi absprechen, wie man das verbessern kann. Mögliche Lösungen:
- Sub-division des Meshes und dann NNVC
- automatisches UV-Mapping und Erzeugung von Texturen aus den Punktwolken.
- Texturen aus den Fotos?"
- Paper: "Texture Defragmentation for Photo-Reconstructed 3D Models" will come to Meshlab
- Interessantes Paper: "Point2color: 3D Point Cloud Colorization Using a Conditional Generative
Network and Differentiable Rendering for Airborne LiDAR"

**Comment by ErlerPhilipp** [comment]
@joschi1212 
very interesting paper, combines surface reconstruction and texturing. "Deep Hybrid Self-Prior for Full 3D Mesh Generation": https://arxiv.org/pdf/2108.08017.pdf
Repo: https://github.com/weixk2015/DHSP3D

**Comment by ErlerPhilipp** [comment]
COLMAP writes the camera poses to binary or text files: https://colmap.github.io/format.html#sparse-reconstruction
I see that the binary version is active in our project, since I have a "cameras.bin" in my local test dir `.\upload\4c5c6d38-255e-4708-b5f8-41e029e36340\step1\v000\sparse\0\`

so, we have the camera poses already available for further processing.

**Comment by ErlerPhilipp** [comment]
one more related paper: https://arxiv.org/pdf/2101.10734.pdf

**Comment by joschi1212** [comment]
Thanks, I will look into it!

**Comment by ErlerPhilipp** [comment]
Maybe, we can take some parts from Alicevision/Meshroom: https://github.com/alicevision/meshroom
Here is some more info from their docu: https://meshroom-manual.readthedocs.io/en/bibtex1/node-reference/nodes/Texturing.html
and  https://meshroom-manual.readthedocs.io/en/latest/feature-documentation/nodes/Texturing.html

Their most interesting reference is Seamless Image-Based Texture Atlases using Multi-band Blending: http://imagine.enpc.fr/publications/papers/ICPR08a.pdf

**Comment by ErlerPhilipp** [comment]
Nerfstudio also has a texturing based on xatlas, see export_textured_mesh(): https://github.com/nerfstudio-project/nerfstudio/blob/4545dcb6b30538013e27ddcdcbcecfc0402c5007/nerfstudio/exporter/texture_utils.py

Not sure if this is better than the current attempt but it combines color extraction and unwrapping. If the NeRF-Variant works, we might switch to Nerfstudio anyway.

**Comment by ErlerPhilipp** [comment]
we want reconstruction and coloring independent of each other to get the best method for each. we checked several methods and packages but didn't find an easy solution yet.
openmvs: how to replace reconstruction?
xatlas: how to project images on mesh (with texture)?
nerfstudio: how to replace nerf with photo?
TEXTure: how to use?
alicevision: how to use texturing? use pipeline except reconstruction?

**Comment by ErlerPhilipp** [comment]
found a repo based on a 2014 paper that solves exactly our problem: mesh+ registered images -> texture
https://github.com/nmoehrle/mvs-texturing
https://www.youtube.com/watch?v=Ie-qLJdmlLI

also this improvement, but sadly without public source: https://cseweb.ucsd.edu/~viscomp/projects/SIG17TextureMapping/

**Comment by ErlerPhilipp** [comment]
still not solved. no available library exactly matches our problem. a seminar paper shows that AliceVision provides the best quality, then OpenMVG. easiest to implement is probably https://github.com/nmoehrle/mvs-texturing
