### ISSUE TITLE
WP 3.1: Better SFM

### ISSUE THREAD

**Issue by ErlerPhilipp** [ErlerPhilipp/Pix2Model#26]
"Genauere Recherche zusammen mit Stefan, um die beste Variante von SFM für die in den Tests gefundenen Bedingungen auszuwählen.
Implementierungsaufwand abwägen.
Implementieren, evtl. in C++, sonst wahrscheinlich in Python."

**Comment by ErlerPhilipp** [comment]
Discuss this with Attila from the VRVis. One option is AliceVision.

Another, more experimental, solution is to try a NeRF with surface extraction.

**Comment by ErlerPhilipp** [comment]
i would prefer Nerfstudio because it has a nicer license

**Comment by ErlerPhilipp** [comment]
Nerfstudio just released a new version with NeuS and NeuSFacto model based on this paper: https://arxiv.org/pdf/2106.10689.pdf
Could be worth a try.

**Comment by ErlerPhilipp** [comment]
interesting paper by a colleague: https://repo-sam.inria.fr/fungraph/3d-gaussian-splatting/
maybe wait and see if it will be included in nerfstudio

**Comment by ErlerPhilipp** [comment]
another interesting work that could replace COLMAP: https://openaccess.thecvf.com/content/CVPR2023/papers/Li_Neuralangelo_High-Fidelity_Neural_Surface_Reconstruction_CVPR_2023_paper.pdf

**Comment by ErlerPhilipp** [comment]
and another: https://liuyuan-pal.github.io/NeRO/

**Comment by ErlerPhilipp** [comment]
the experiments so far were not convincing. all nerf methods have either too strict requirements to the inputs (accurate camera poses, images from all sides etc.) or worse quality than COLMAP (although the paper results look better)

**Comment by ErlerPhilipp** [comment]
had a longer discussion with a visitor... NeuS and derivates are probably the way to go. we care about the geometry, which typical NeRFs can't represent properly.
note that we need a version without segmentation masks that also works on unbounded scenes. apparently, they all depend on COLMAP for camera poses.

NeuS (rather slow): https://github.com/Totoro97/NeuS
NeuDA (slow?): https://github.com/3D-FRONT-FUTURE/NeuDA
NeuS++ (faster, check branch for unmasked): https://github.com/19reborn/NeuS2/tree/neuspp
Instant Neural Surface Reconstruction(fast): https://github.com/bennyguo/instant-nsr-pl
NeRO (slow?, no unbounded scenes?): https://github.com/liuyuan-pal/NeRO
Neuralangelo (need license): https://research.nvidia.com/labs/dir/neuralangelo/
SDFStudio (like NeRFStudio but for reconstruction, check license for angelo): https://github.com/autonomousvision/sdfstudio

most interesting seem SDFStudio and NeuS++

**Comment by hugoycj** [comment]
@ErlerPhilipp Hi Philipp. I have recently released a derivative version of Neus and Neuralangelo called [Instant-angelo](https://github.com/hugoycj/Instant-angelo). This new project has a friendly open-source license, higher efficiency, and is fully compatible with Colmap. Additionally, while our current reconstruction pipeline does not use masking, it focuses on reconstructing just the central area within the camera poses' field of view. I hope this new project will be useful to the research community. We provide some [visualization](https://github.com/hugoycj/Instant-angelo_vis) of current results. Please let me know if you have any other questions!

**Comment by ErlerPhilipp** [comment]
Hi @hugoycj ! Thanks, your work looks indeed very interesting.
I have several questions:
1. There is no official publication, right? Do you plan to publish it?
2. Are the implementation details described or documented somewhere or should I just look at the code?
3. Can I download some results as textured meshes? I see only GIFs in your repo.
4. In case you have the time, I would really appreciate if you could run this example with your method: https://drive.google.com/drive/folders/1AgSzlI884Hezh4ebPBe5dITLAI8fX4He?usp=sharing

**Comment by hugoycj** [comment]
Apologies for the delayed response as I am currently occupied with the deadline for a conference.

Instant-Angelo is still in the developmental phase. Its functionality heavily relies on the results obtained through sfm (structure from motion) and may encounter issues if the sfm points are noisy or sparse. Our main objective for developing Instant-Angelo is to provide a useful tool for the community, and we have not yet a plan for publication. However, we intend to create a blog and detailed documentation once I complete the deadline in mid-November. 

Currently, only geometry mesh export is supported in Instant-Angelo, but we are working tirelessly to incorporate a new API for exporting textured mesh. 

For reference, I have run the example on your provided data. The process takes 2 minutes for structure-from-motion and 20 minutes on 3090 for dense reconstruction. You could download the geometry mesh from [this link](https://cuhko365-my.sharepoint.com/:u:/g/personal/118010378_link_cuhk_edu_cn/ERaT_f40M1ZCsJL7o4jNGvAB-q2C8TsxLZizgouHRIS1ag?e=Q8gSHP). Some quick look up results are shown below:
![Screenshot from 2023-11-03 00-25-30](https://github.com/ErlerPhilipp/Pix2Model/assets/40767265/c7efd214-73c5-4bc2-8af8-b635427f37d6)
![Screenshot from 2023-11-03 00-25-49](https://github.com/ErlerPhilipp/Pix2Model/assets/40767265/368fec41-484a-4d47-9493-f45e3e5d6a7f)
![Screenshot from 2023-11-03 00-25-58](https://github.com/ErlerPhilipp/Pix2Model/assets/40767265/deb6703f-5a1c-4213-831f-dede2b98d9dc)



![Screenshot from 2023-11-03 00-26-12](https://github.com/ErlerPhilipp/Pix2Model/assets/40767265/0cc79058-459c-4bb9-b951-ae951a802c5f)

**Comment by ErlerPhilipp** [comment]
Sorry for the delay on my side, this time. Good luck with your submission!

Thank you so much for running it on our example. This result looks indeed pretty good. Interesting that it creates a hole in the bottom plate while it fills in the space between the feet. 

We're currently switching from COLMAP to AliceVision, which is way more modular. Once this is done, we can replace e.g. the SfM/MVS part with a NeRF/NeuS variant. Your method is definitely a hot candidate for that. Thanks!

**Comment by ErlerPhilipp** [comment]
switching to AliceVision or other methods is too much work for now
