### ISSUE TITLE
Impressum und Datenschutzerklärung (muss dann noch angepasst werden) von CG Seite kopieren:

### ISSUE THREAD

**Issue by sophie-sudoku** [ErlerPhilipp/Pix2Model#48]
https://www.cg.tuwien.ac.at/content/Datenschutzerkl%C3%A4rung
https://www.cg.tuwien.ac.at/impressum
Unter Team einfügen?

**Comment by sophie-sudoku** [comment]
can you pls give me a heads up when the changes to that page are finalized - is there an english translation i can use?

Should i maybe add a footer for Datenschutz and Impressum, which is accessible on every tab?

**Comment by ErlerPhilipp** [comment]
> can you pls give me a heads up when the changes to that page are finalized - is there an english translation i can use?
please use the german versions from the cg webpage for now. i'll modify them in the code.

> Should i maybe add a footer for Datenschutz and Impressum, which is accessible on every tab?
yes, that's probably better. shouldn't take too much space on the screen though.

**Comment by ErlerPhilipp** [comment]
updated. needs a simple touch when SSL is active and when the automatic deletion of data is implemented

**Comment by sophie-sudoku** [comment]
remove "not implemented" for "ssl" and "hochgeladene daten und deren verarbeitungsergebnisse"
