### ISSUE TITLE
Schöneres Beispiel. Die P2S Bilder waren eigentlich nur Platzhalter und haben nicht viel mit Pics2Model zu tun.

### ISSUE THREAD

**Issue by sophie-sudoku** [ErlerPhilipp/Pix2Model#49]

**Comment by sophie-sudoku** [comment]
which ones can we use?

**Comment by ErlerPhilipp** [comment]
i'll try to make a good example this weekend. surely, something will come up during the tests

**Comment by ErlerPhilipp** [comment]
new example is on its way. i'll upload it and send you a message on discord
![snapshot00](https://user-images.githubusercontent.com/7949665/154803986-15202a1d-0dbd-4164-81b5-01be1a9a82fd.png)
