### ISSUE TITLE
Upload error

### ISSUE THREAD

**Issue by ErlerPhilipp** [ErlerPhilipp/Pix2Model#53]
Got the same error for all uploaded images:
![image](https://user-images.githubusercontent.com/7949665/154798766-294ec465-275e-4450-a30d-2afb525294c2.png)

Any idea what the reason might be?
Display error without HTML tags?

**Comment by ErlerPhilipp** [comment]
checked htop a bit later on the server. it showed that no processing step was running.

**Comment by sophie-sudoku** [comment]
the backend connection is missing on the netidee server - the backend always responds with 500 for every request
locally it is working fine

**Comment by ErlerPhilipp** [comment]
akiwa checked the server and it looked like it was a consequence of a too small partition for user data, which was probably a strange default setting from somewhere
