### ISSUE TITLE
Editor keeps GPU busy although there is nothing to display

### ISSUE THREAD

**Issue by ErlerPhilipp** [ErlerPhilipp/Pix2Model#54]
Taskmanager shows that the editor keeps the GPU busy:
![image](https://user-images.githubusercontent.com/7949665/154799385-44ce1764-7748-4615-82b2-c4bfeed323c2.png)

although there is not yet anything to display:
![image](https://user-images.githubusercontent.com/7949665/154799417-8cd5004a-9278-4bfe-86b8-c0a6cb3599f1.png)

Stop render loop until the object is ready?

**Comment by ErlerPhilipp** [comment]
looks pretty good. one issue i found is: when i re-size the browser window, the editor stays black

**Comment by ErlerPhilipp** [comment]
changing the light intensity doesn't trigger the rendering

**Comment by sophie-sudoku** [comment]
**updated**

**Comment by ErlerPhilipp** [comment]
works. i don't find any more problems.
