### ISSUE TITLE
Multi-threaded Poisson Rec

### ISSUE THREAD

**Issue by ErlerPhilipp** [ErlerPhilipp/Pix2Model#56]
There is a new release of PyMeshlab: https://github.com/cnr-isti-vclab/meshlab/discussions/1218
> possibility to select number of threads in filter screened poisson

@thefloff Is this worth a try? Was it single threaded before or used all available cores?

Be careful with the update, they apparently changed the filter names.

**Comment by thefloff** [comment]
Currently it is using all cores. I don't see a reason why we would want to change that.
Maybe in the future if we want to have two reconstructions running in parallel?
I would not update pymeshlab for this feature for now

**Comment by ErlerPhilipp** [comment]
ok, using all cores is fine.
