### ISSUE TITLE
Abort Job (API Endpunkt und FE button)

### ISSUE THREAD

**Issue by sophie-sudoku** [ErlerPhilipp/Pix2Model#59]
send_stop_job_command responds with an job-not-found exception, which is due to a different naming scheme for the jobs compared to the folders that are created for a job (i think)

**Comment by akiwa** [comment]
I pushed the new route to this branch [feature/abort-job](https://github.com/ErlerPhilipp/Pix2Model/tree/feature/abort-job).

**Comment by sophie-sudoku** [comment]
needs testing

**Comment by ErlerPhilipp** [comment]
doesn't look right:
![image](https://user-images.githubusercontent.com/7949665/159172858-6b06a9ff-7eb9-4cf5-8077-c01f0be0f84b.png)

**Comment by ErlerPhilipp** [comment]
there is no log link visible, but when i click where it should be, i get the log of a different upload (different UID): `blob:http://netidee.cg.tuwien.ac.at/403a77d4-909e-4374-8905-648c1044aba1`

**Comment by ErlerPhilipp** [comment]
after abort job, you can abort again:
![grafik](https://user-images.githubusercontent.com/7949665/174499187-a708f0b9-3b47-4fc4-8269-f1c3e633ea2c.png)

make abort invisible? don't forget to make it visible again when necessary.

**Comment by sophie-sudoku** [comment]
**update**

**Comment by ErlerPhilipp** [comment]
looks good
