### ISSUE TITLE
Submit images while submitting images

### ISSUE THREAD

**Issue by ErlerPhilipp** [ErlerPhilipp/Pix2Model#76]
You can click on the drop area to upload more images while the upload of one job runs. However, the additional images are not enqueued with the other ones. If you click again on submit, the second ones are submitted to a another job. 

Looks like it works but it's a strange mixup of separate jobs. Also, only one result link is show. The easiest and best solution is probably to disable additional file drops while the upload runs.

**Comment by sophie-sudoku** [comment]
fixed
